# Usa la imagen oficial de Node como base
FROM node:14-alpine

# Define el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos package.json y package-lock.json (o yarn.lock si usas Yarn)
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos de la aplicación
COPY . .

# Construye la aplicación de React Native (ajusta el comando según tu proyecto)
RUN npm run build

# Expone el puerto en el que se ejecutará el servidor de desarrollo de React Native (generalmente 8081)
EXPOSE 8081

# Ejecuta el servidor de desarrollo de React Native
CMD ["npm", "start"]